### ISSUE TITLE
Can not view weather data

### ISSUE THREAD

**Issue by kareemtawab** [wiz78/WeatherClock#4]
Hi.

I managed to get the Pi up and running with the chromium kiosk setup and added the following line to a bash script:

`/usr/bin/chromium-browser --noerrdialogs --enable-features=OverlayScrollbar --disable-infobars --kiosk --force-device-scale-factor=1.2  file:///home/pi/WeatherClock/index.html &`

However, I'm only getting the date and the time centred on the screen without any weather data. Am I missing something? I need help.

**Comment by wiz78** [comment]
you can't use file:// to serve the website, since it needs PHP to run its code. You need to install apache + mod_php, or nginx + php, and use something like http://localhost/WeatherClock/ (supposing you copy WeatherClock into the document root, which might be /var/www/html)

You can read https://www.raspberrypi.org/documentation/remote-access/web-server/apache.md to get you started, for instance.

**Comment by kareemtawab** [comment]
Thanks a lot! I got it working now!
